<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2018.1.1.386
*/

require_once('form_process.php');

$form = array(
	'subject' => 'Schullizenz Formular Übermittlung',
	'heading' => 'Neue Formularübermittlung',
	'success_redirect' => 'danke.html',
	'resources' => array(
		'checkbox_checked' => 'Aktiviert',
		'checkbox_unchecked' => 'Nicht aktiviert',
		'submitted_from' => 'Von Website übermitteltes Formular: %s',
		'submitted_by' => 'Besucher-IP-Adresse: %s',
		'too_many_submissions' => 'Zu viele Sendungen in letzter Zeit von dieser IP',
		'failed_to_send_email' => 'E-Mail konnte nicht gesendet werden',
		'invalid_reCAPTCHA_private_key' => 'Ungültiger privater reCAPTCHA-Schlüssel.',
		'invalid_reCAPTCHA2_private_key' => 'Ungültiger privater reCAPTCHA 2.0-Schlüssel.',
		'invalid_reCAPTCHA2_server_response' => 'Ungültige private reCAPTCHA 2.0-Server-Reaktionszeit.',
		'invalid_field_type' => 'Unbekannter Feldtyp „%s“.',
		'invalid_form_config' => 'Die Konfiguration im Feld „%s“ ist ungültig.',
		'unknown_method' => 'Unbekannte Serveranfragemethode'
	),
	'email' => array(
		'from' => 'willy.brunner@t-online.de',
		'to' => 'willy.brunner@t-online.de'
	),
	'fields' => array(
		'custom_U2935' => array(
			'order' => 1,
			'type' => 'string',
			'label' => 'Name Ansprechpartner',
			'required' => true,
			'errors' => array(
				'required' => 'Feld „Name Ansprechpartner“ ist erforderlich.'
			)
		),
		'Email' => array(
			'order' => 2,
			'type' => 'email',
			'label' => 'E-Mail',
			'required' => true,
			'errors' => array(
				'required' => 'Feld „E-Mail“ ist erforderlich.',
				'format' => 'Die E-Mail-Adresse in Feld „E-Mail“ ist ungültig.'
			)
		),
		'custom_U2927' => array(
			'order' => 3,
			'type' => 'string',
			'label' => 'Schule',
			'required' => true,
			'errors' => array(
				'required' => 'Feld „Schule“ ist erforderlich.'
			)
		),
		'custom_U2943' => array(
			'order' => 11,
			'type' => 'string',
			'label' => 'Anmerkung zur Bestellung',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U2931' => array(
			'order' => 4,
			'type' => 'string',
			'label' => 'Straße',
			'required' => true,
			'errors' => array(
				'required' => 'Feld „Straße“ ist erforderlich.'
			)
		),
		'custom_U2919' => array(
			'order' => 5,
			'type' => 'string',
			'label' => 'Ort',
			'required' => true,
			'errors' => array(
				'required' => 'Feld „Ort“ ist erforderlich.'
			)
		),
		'custom_U2947' => array(
			'order' => 6,
			'type' => 'string',
			'label' => 'PLZ',
			'required' => true,
			'errors' => array(
				'required' => 'Feld „PLZ“ ist erforderlich.'
			)
		),
		'custom_U2923' => array(
			'order' => 7,
			'type' => 'string',
			'label' => 'Land',
			'required' => true,
			'errors' => array(
				'required' => 'Feld „Land“ ist erforderlich.'
			)
		),
		'custom_U2939' => array(
			'order' => 8,
			'type' => 'string',
			'label' => 'Stückzahl zu je 49€ incl. MwSt',
			'required' => true,
			'errors' => array(
				'required' => 'Feld „Stückzahl zu je 49€ incl. MwSt“ ist erforderlich.'
			)
		),
		'custom_U2952' => array(
			'order' => 9,
			'type' => 'checkbox',
			'label' => 'Allgemeine Geschäftsbedingungen',
			'required' => true,
			'errors' => array(
				'required' => 'Feld „Allgemeine Geschäftsbedingungen“ ist erforderlich.'
			)
		),
		'custom_U2956' => array(
			'order' => 10,
			'type' => 'checkbox',
			'label' => 'Widerrufsbelehrung',
			'required' => true,
			'errors' => array(
				'required' => 'Feld „Widerrufsbelehrung“ ist erforderlich.'
			)
		)
	)
);

process_form($form);
?>
