<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2018.1.1.386
*/

require_once('form_process.php');

$form = array(
	'subject' => 'Disponieren Formular Übermittlung',
	'heading' => 'Neue Formularübermittlung',
	'success_redirect' => 'danke.html',
	'resources' => array(
		'checkbox_checked' => 'Aktiviert',
		'checkbox_unchecked' => 'Nicht aktiviert',
		'submitted_from' => 'Von Website übermitteltes Formular: %s',
		'submitted_by' => 'Besucher-IP-Adresse: %s',
		'too_many_submissions' => 'Zu viele Sendungen in letzter Zeit von dieser IP',
		'failed_to_send_email' => 'E-Mail konnte nicht gesendet werden',
		'invalid_reCAPTCHA_private_key' => 'Ungültiger privater reCAPTCHA-Schlüssel.',
		'invalid_reCAPTCHA2_private_key' => 'Ungültiger privater reCAPTCHA 2.0-Schlüssel.',
		'invalid_reCAPTCHA2_server_response' => 'Ungültige private reCAPTCHA 2.0-Server-Reaktionszeit.',
		'invalid_field_type' => 'Unbekannter Feldtyp „%s“.',
		'invalid_form_config' => 'Die Konfiguration im Feld „%s“ ist ungültig.',
		'unknown_method' => 'Unbekannte Serveranfragemethode'
	),
	'email' => array(
		'from' => 'willy.brunner@t-online.de',
		'to' => 'willy.brunner@t-online.de'
	),
	'fields' => array(
		'custom_U3025' => array(
			'order' => 1,
			'type' => 'string',
			'label' => 'Art der Vorführung',
			'required' => true,
			'errors' => array(
				'required' => 'Feld „Art der Vorführung“ ist erforderlich.'
			)
		),
		'custom_U3052' => array(
			'order' => 3,
			'type' => 'string',
			'label' => 'Spielort',
			'required' => true,
			'errors' => array(
				'required' => 'Feld „Spielort“ ist erforderlich.'
			)
		),
		'custom_U3064' => array(
			'order' => 15,
			'type' => 'string',
			'label' => 'Anmerkung zur Bestellung',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U3029' => array(
			'order' => 10,
			'type' => 'string',
			'label' => 'Straße',
			'required' => true,
			'errors' => array(
				'required' => 'Feld „Straße“ ist erforderlich.'
			)
		),
		'custom_U3043' => array(
			'order' => 11,
			'type' => 'string',
			'label' => 'Ort',
			'required' => true,
			'errors' => array(
				'required' => 'Feld „Ort“ ist erforderlich.'
			)
		),
		'custom_U3039' => array(
			'order' => 12,
			'type' => 'string',
			'label' => 'PLZ',
			'required' => true,
			'errors' => array(
				'required' => 'Feld „PLZ“ ist erforderlich.'
			)
		),
		'custom_U3060' => array(
			'order' => 13,
			'type' => 'string',
			'label' => 'Land',
			'required' => true,
			'errors' => array(
				'required' => 'Feld „Land“ ist erforderlich.'
			)
		),
		'custom_U3048' => array(
			'order' => 14,
			'type' => 'checkbox',
			'label' => 'Allgemeine Geschäftsbedingungen',
			'required' => true,
			'errors' => array(
				'required' => 'Feld „Allgemeine Geschäftsbedingungen“ ist erforderlich.'
			)
		),
		'custom_U3173' => array(
			'order' => 4,
			'type' => 'string',
			'label' => 'Theater',
			'required' => true,
			'errors' => array(
				'required' => 'Feld „Theater“ ist erforderlich.'
			)
		),
		'custom_U3185' => array(
			'order' => 5,
			'type' => 'string',
			'label' => 'Telefonnummer Theater',
			'required' => true,
			'errors' => array(
				'required' => 'Feld „Telefonnummer Theater“ ist erforderlich.'
			)
		),
		'custom_U3197' => array(
			'order' => 6,
			'type' => 'string',
			'label' => 'e-Mail Adresse Theater',
			'required' => true,
			'errors' => array(
				'required' => 'Feld „e-Mail Adresse Theater“ ist erforderlich.'
			)
		),
		'custom_U3209' => array(
			'order' => 7,
			'type' => 'string',
			'label' => 'Disponent',
			'required' => true,
			'errors' => array(
				'required' => 'Feld „Disponent“ ist erforderlich.'
			)
		),
		'custom_U3221' => array(
			'order' => 8,
			'type' => 'string',
			'label' => 'Telefonnummer Disponent',
			'required' => true,
			'errors' => array(
				'required' => 'Feld „Telefonnummer Disponent“ ist erforderlich.'
			)
		),
		'custom_U3233' => array(
			'order' => 9,
			'type' => 'string',
			'label' => 'e-Mail Disponent',
			'required' => true,
			'errors' => array(
				'required' => 'Feld „e-Mail Disponent“ ist erforderlich.'
			)
		),
		'custom_U3321' => array(
			'order' => 2,
			'type' => 'string',
			'label' => 'Gewünschter Zeitraum',
			'required' => true,
			'errors' => array(
				'required' => 'Feld „Gewünschter Zeitraum“ ist erforderlich.'
			)
		)
	)
);

process_form($form);
?>
